image:
  repository: 119609063969.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-ecr
  tag: v1.0.7
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd 